export const providerList = [
  {
    bio: "Lorem ipsum is your friend",
    designation: "MD",
    firstName: "John",
    gender: "Male",
    id: 1,
    imageUrl: "",
    languages: ["English"],
    lastName: "Doe",
    locations: [],
    middleInitial: "A",
    npi: "123456789",
    proceduresAndConditions: [],
    slug: "John-Doe-MD",
    specialties: [],
    website: "https://tcaheart.com",
  },
  {
    bio: "Lorem ipsum is your friend",
    designation: "MD",
    firstName: "Jane",
    gender: "Female",
    id: 2,
    imageUrl: "",
    languages: ["English", "German"],
    lastName: "Doe",
    locations: [],
    middleInitial: "E",
    npi: "112345678",
    proceduresAndConditions: [],
    slug: "Jane-Doe-MD",
    specialties: [],
    website: "https://tcaheart.com",
  },
];
